## 모델링 아이디어 구현 1


- 426개의 행정동 -> 군집화
    - k-means 클러스터링 사용
-  해당 집단 내에서 유저입력과 가장 가까운 거리에 있는 동을 1개 추출 
    - 코사인 유사도 측정
   
- 해당 동과 유사한 동을 콘텐츠 기반 추천으로 가져옴
    - 유사 매트릭스 사용

In [151]:
from sklearn.datasets import load_iris
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
%matplotlib inline

In [152]:
tmp_df = pd.read_csv('tmp_data.csv')
tmp_df.columns = ['행정동명','A','B','C','D']
tmp_df.head()

행정동명         A         B         C         D
0  사직동  0.756808  0.837151  0.367741  0.856218
1  삼청동  0.827742  0.304679  0.923518  0.000679
2  부암동  0.568917  0.924518  0.056251  0.260088
3  평창동  0.580705  0.584580  0.844815  0.060866
4  무악동  0.139818  0.303443  0.598331  0.312935

In [153]:
data = tmp_df[['A','B','C','D']]
data.head()

A         B         C         D
0  0.756808  0.837151  0.367741  0.856218
1  0.827742  0.304679  0.923518  0.000679
2  0.568917  0.924518  0.056251  0.260088
3  0.580705  0.584580  0.844815  0.060866
4  0.139818  0.303443  0.598331  0.312935

In [154]:
data = tmp_df[['A','B','C','D']]
kmeans = KMeans(n_clusters=10, init='k-means++', max_iter=300, random_state=0)
kmeans.fit(data)

C:\Users\yorijori\AppData\Roaming\Python\Python39\site-packages\sklearn\cluster\_kmeans.py:1334: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.
  warnings.warn(


KMeans(n_clusters=10, random_state=0)

In [155]:
tmp_df['cluster'] = kmeans.labels_
tmp_df.head()

행정동명         A         B         C         D  cluster
0  사직동  0.756808  0.837151  0.367741  0.856218        9
1  삼청동  0.827742  0.304679  0.923518  0.000679        3
2  부암동  0.568917  0.924518  0.056251  0.260088        0
3  평창동  0.580705  0.584580  0.844815  0.060866        8
4  무악동  0.139818  0.303443  0.598331  0.312935        4

In [156]:
input_data = { "A" : 0.1, "B" : 0.2 ,"C": 0.4, "D":0.3}
user_data = pd.DataFrame(input_data, index=[len(tmp_df)])
user_data

A    B    C    D
426  0.1  0.2  0.4  0.3

In [157]:
prediction = kmeans.predict(test_data)
prediction

array([4])

In [158]:
# test_data['cluster'] = prediction

In [159]:
sim_group = tmp_df[tmp_df['cluster']== prediction[0]]
sim_group_indexes = sim_group.index.values
sim_group_indexes 

array([  4,  10,  34,  84,  88,  95, 132, 134, 154, 158, 175, 186, 188,
       208, 214, 217, 229, 250, 276, 282, 295, 307, 323, 326, 328, 351,
       356, 358, 370, 386, 391, 404, 405, 417], dtype=int64)

In [178]:
sim_df = tmp_df.iloc[sim_group_indexes]
sim_df

행정동명         A         B         C         D  cluster
4      무악동  0.139818  0.303443  0.598331  0.312935        4
10     혜화동  0.265030  0.047449  0.968052  0.331414        4
34     남영동  0.461374  0.239996  0.862594  0.062068        4
84     용신동  0.036078  0.113723  0.470046  0.322846        4
88   답십리1동  0.133258  0.269984  0.619889  0.015625        4
95    면목4동  0.024411  0.074767  0.564713  0.074528        4
132    번3동  0.255324  0.088114  0.591840  0.293693        4
134   수유2동  0.032760  0.235101  0.420575  0.325524        4
154    창5동  0.198148  0.339093  0.400281  0.260535        4
158   월계2동  0.049067  0.474501  0.562824  0.081430        4
175   공릉1동  0.185288  0.087887  0.762164  0.028030        4
186    증산동  0.399825  0.281202  0.672616  0.065299        4
188    진관동  0.334812  0.273711  0.655902  0.314856        4
208    염리동  0.231781  0.098179  0.352774  0.153678        4
214    연남동  0.023969  0.308224  0.486862  0.297279        4
217    상암동  0.553857  0.232783  0.557085  0.055514        4
229   신월3동  0.434336  0.011109  0.740507  0.082528        4
250   가양1동  0.055849  0.180132  0.251873  0.119218        4
276    가산동  0.021307  0.208386  0.970664  0.078230        4
282   시흥2동  0.122389  0.416999  0.839198  0.370983        4
295   신길6동  0.443615  0.297556  0.588997  0.054741        4
307   상도3동  0.206334  0.415162  0.833821  0.068589        4
323    중앙동  0.453560  0.020089  0.436201  0.118986        4
326    서원동  0.234027  0.201886  0.474324  0.000780        4
328    서림동  0.454221  0.078933  0.713121  0.252643        4
351   방배1동  0.200954  0.441691  0.923492  0.039787        4
356   양재2동  0.264601  0.291242  0.970776  0.197308        4
358    신사동  0.199498  0.028280  0.698478  0.359021        4
370   개포1동  0.254999  0.394121  0.578185  0.180091        4
386   방이1동  0.023669  0.578284  0.871653  0.105674        4
391   송파2동  0.275845  0.319749  0.668446  0.017782        4
404   잠실4동  0.100250  0.064045  0.618725  0.353803        4
405   잠실6동  0.446965  0.201510  0.997252  0.187159        4
417   천호2동  0.373507  0.136070  0.788253  0.396430        4

In [160]:
sim_datas = data.iloc[sim_group_indexes]
sim_datas.head()

A         B         C         D
4   0.139818  0.303443  0.598331  0.312935
10  0.265030  0.047449  0.968052  0.331414
34  0.461374  0.239996  0.862594  0.062068
84  0.036078  0.113723  0.470046  0.322846
88  0.133258  0.269984  0.619889  0.015625

In [161]:
user_con_data = pd.concat([user_data, sim_datas])
user_con_data.head()

A         B         C         D
426  0.100000  0.200000  0.400000  0.300000
4    0.139818  0.303443  0.598331  0.312935
10   0.265030  0.047449  0.968052  0.331414
34   0.461374  0.239996  0.862594  0.062068
84   0.036078  0.113723  0.470046  0.322846

In [165]:
from sklearn.metrics.pairwise import cosine_similarity

dong_sim = cosine_similarity(user_con_data,user_con_data) # 유사도 행렬
dong_sim.shape # 유사도 행렬의 크기

(35, 35)

In [172]:
cols = user_con_data.index
pd.DataFrame(data=dong_sim,columns=cols,index=cols).head()

426       4         10        34        84        88        95   \
426  1.000000  0.988488  0.901856  0.828236  0.975333  0.847471  0.843434   
4    0.988488  1.000000  0.921328  0.885062  0.961100  0.917276  0.894076   
10   0.901856  0.921328  1.000000  0.926524  0.936050  0.895886  0.955620   
34   0.828236  0.885062  0.926524  1.000000  0.798472  0.951606  0.897763   
84   0.975333  0.961100  0.936050  0.798472  1.000000  0.826553  0.892207   

          132       134       154  ...       328       351       356  \
426  0.941284  0.991183  0.962280  ...  0.870156  0.856518  0.911594   
4    0.945555  0.978734  0.969503  ...  0.888766  0.924519  0.956342   
10   0.982660  0.867985  0.829125  ...  0.958200  0.888479  0.965700   
34   0.926948  0.773357  0.856169  ...  0.961146  0.947087  0.968337   
84   0.943252  0.974657  0.882676  ...  0.856596  0.829335  0.906100   

          358       370       386       391       404       405       417  
426  0.929337  0.928401  0.865256  0.840879  0.951189  0.874947  0.941028  
4    0.927856  0.965892  0.925701  0.908197  0.944876  0.917459  0.945335  
10   0.990117  0.870472  0.820139  0.885865  0.975517  0.969071  0.976550  
34   0.884400  0.933948  0.855734  0.979459  0.846520  0.990502  0.931327  
84   0.962503  0.860096  0.833167  0.794917  0.988068  0.865499  0.935540  

[5 rows x 35 columns]

In [219]:
dong_sim.argsort()[:,::-1][0][1:3]

array([8, 1], dtype=int64)

In [237]:
best_sim_index = dong_sim.argsort()[:,::-1][0][1]
user_con_data.iloc[[best_sim_index]]

A         B         C         D
134  0.03276  0.235101  0.420575  0.325524

In [240]:
best_dong_index = user_con_data.iloc[[best_sim_index]].index.values
best_dong_idx = best_dong_index[0]
best_dong_idx

134

In [241]:
best_dong = tmp_df.iloc[[best_dong_idx]]
best_dong

행정동명        A         B         C         D  cluster
134  수유2동  0.03276  0.235101  0.420575  0.325524        4

### 전체 동에 대한 유사도 측정

In [242]:
total_sim = cosine_similarity(data,data) # 유사도 행렬
total_sim.shape

(426, 426)

In [245]:
sim_index_arr = total_sim[:,best_dong_idx].argsort()[::-1][:10]
sim_index_arr

array([134, 258,  92, 292, 241, 214,  69,  74, 220, 272], dtype=int64)

In [247]:
tmp_df.iloc[sim_index_arr]

행정동명         A         B         C         D  cluster
134  수유2동  0.032760  0.235101  0.420575  0.325524        4
258  화곡1동  0.134364  0.491884  0.970037  0.672307        7
92   이문1동  0.081691  0.504579  0.994944  0.597910        7
292  신길3동  0.082351  0.357668  0.766452  0.468278        7
241  등촌1동  0.123554  0.361745  0.714388  0.450951        7
214   연남동  0.023969  0.308224  0.486862  0.297279        4
69   중곡3동  0.047204  0.858605  0.997501  0.876292        7
74   구의3동  0.187565  0.469875  0.850806  0.928411        7
220   공덕동  0.029025  0.284269  0.968177  0.775278        7
272   수궁동  0.184669  0.649466  0.807392  0.915070        7

In [253]:
user_data

A    B    C    D
426  0.1  0.2  0.4  0.3

In [255]:
tmp_df.iloc[sim_index_arr[:3]]

행정동명         A         B         C         D  cluster
134  수유2동  0.032760  0.235101  0.420575  0.325524        4
258  화곡1동  0.134364  0.491884  0.970037  0.672307        7
92   이문1동  0.081691  0.504579  0.994944  0.597910        7

## 최종 추천 동
- 유저 입력과 군집에서 가장 가까운 수유2동
- 전체 동에서 수유2동과 가장 가까운 화곡1동, 이문1동